export const ALL_INSURANCES_REQUEST = 'ALL_INSURANCES_REQUEST';
export const ALL_INSURANCES_SUCCESS = 'ALL_INSURANCES_SUCCESS';
export const ALL_INSURANCES_FAIL = 'ALL_INSURANCES_FAIL';

export const LOAD_INSURANCE_REQUEST = 'LOAD_INSURANCE_REQUEST';
export const LOAD_INSURANCE_SUCCESS = 'LOAD_INSURANCE_SUCCESS';
export const LOAD_INSURANCE_FAIL = 'LOAD_INSURANCE_FAIL';

export const UPDATE_INSURANCE_REQUEST = 'UPDATE_INSURANCE_REQUEST';
export const UPDATE_INSURANCE_SUCCESS = 'UPDATE_INSURANCE_SUCCESS';
export const UPDATE_INSURANCE_RESET = 'UPDATE_INSURANCE_RESET';
export const UPDATE_INSURANCE_FAIL = 'UPDATE_INSURANCE_FAIL';

export const DELETE_INSURANCE_REQUEST = 'DELETE_INSURANCE_REQUEST';
export const DELETE_INSURANCE_SUCCESS = 'DELETE_INSURANCE_SUCCESS';
export const DELETE_INSURANCE_FAIL = 'DELETE_INSURANCE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
