export const ALL_PAYMENTS_REQUEST = 'ALL_PAYMENTS_REQUEST';
export const ALL_PAYMENTS_SUCCESS = 'ALL_PAYMENTS_SUCCESS';
export const ALL_PAYMENTS_FAIL = 'ALL_PAYMENTS_FAIL';

export const ADD_PAYMENT_REQUEST = 'ADD_PAYMENT_REQUEST';
export const ADD_PAYMENT_SUCCESS = 'ADD_PAYMENT_SUCCESS';
export const ADD_PAYMENT_FAIL = 'ADD_PAYMENT_FAIL';

export const UPDATE_PAYMENT_REQUEST = 'UPDATE_PAYMENT_REQUEST';
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS';
export const UPDATE_PAYMENT_RESET = 'UPDATE_PAYMENT_RESET';
export const UPDATE_PAYMENT_FAIL = 'UPDATE_PAYMENT_FAIL';

export const DELETE_PAYMENT_REQUEST = 'DELETE_PAYMENT_REQUEST';
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS';
export const DELETE_PAYMENT_FAIL = 'DELETE_PAYMENT_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
