export const ALL_VEHICLES_REQUEST = 'ALL_VEHICLES_REQUEST';
export const ALL_VEHICLES_SUCCESS = 'ALL_VEHICLES_SUCCESS';
export const ALL_VEHICLES_FAIL = 'ALL_VEHICLES_FAIL';

export const LOAD_VEHICLE_REQUEST = 'LOAD_VEHICLE_REQUEST';
export const LOAD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS';
export const LOAD_VEHICLE_FAIL = 'LOAD_VEHICLE_FAIL';

export const ADD_VEHICLE_REQUEST = 'LOAD_VEHICLE_REQUEST';
export const ADD_VEHICLE_SUCCESS = 'LOAD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_FAIL = 'LOAD_VEHICLE_FAIL';

export const UPDATE_VEHICLE_REQUEST = 'UPDATE_VEHICLE_REQUEST';
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS';
export const UPDATE_VEHICLE_RESET = 'UPDATE_VEHICLE_RESET';
export const UPDATE_VEHICLE_FAIL = 'UPDATE_VEHICLE_FAIL';

export const DELETE_VEHICLE_REQUEST = 'DELETE_VEHICLE_REQUEST';
export const DELETE_VEHICLE_SUCCESS = 'DELETE_VEHICLE_SUCCESS';
export const DELETE_VEHICLE_FAIL = 'DELETE_VEHICLE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
